package domain.login

object UserState {
  def EXPIRED="EXPIRED"
  def SUSPENDED="SUSPENDED"
  def CURRENT="CURRENT"
  def VALIDATED="VALIDATED"
  def NOTVALIDATED="NOT VALIDATED"
  def REVOKED="REVOKED"
}
