package util

object GenericLookupData {

  def GENERICSTATUS = Seq(APPKeys.INCOMPLETE, APPKeys.COMPLETE, APPKeys.REJECTED, APPKeys.APPROVED)

  def GENERIC_APPLICANT = Seq(APPKeys.MATRIC_APPLICANT_TYPE)

}
